using System.ComponentModel.DataAnnotations;

namespace Cogstate.Shared.Models.Enums;

public enum Country
{
    Argentina,
    Australia,
    Austria,
    Belgium,
    Brazil,
    Canada,
    Chile,
    China,
    Colombia,
    Croatia,
    [Display(Name = "Czech Republic")] CzechRepublic,
    Denmark,
    Finland,
    France,
    Germany,
    [Display(Name = "Hong Kong")] HongKong,
    Hungary,
    India,
    Israel,
    Italy,
    Japan,
    [Display(Name = "Latin America")] LatinAmerica,
    Mexico,
    Netherlands,
    Norway,
    Peru,
    Poland,
    Portugal,
    [Display(Name = "Puerto Rico")] PuertoRico,
    Romania,
    Russia,
    [Display(Name = "Saudi Arabia")] SaudiArabia,
    Singapore,
    Slovakia,
    [Display(Name = "South Africa")] SouthAfrica,
    [Display(Name = "South Korea")] SouthKorea,
    Spain,
    Sweden,
    Switzerland,
    Taiwan,
    Thailand,
    Turkey,
    [Display(Name = "United Kingdom")] UnitedKingdom,
    [Display(Name = "United States")] UnitedStates
}