using System.ComponentModel.DataAnnotations;

namespace Cogstate.Shared.Models.Enums;

public enum Language
{
    Arabic,
    Bengali,
    Catalan,
    Croatian,
    Czech,
    Danish,
    Dutch,
    English,
    Finnish,
    French,
    German,
    Gujarati,
    Hebrew,
    Hindi,
    Hungarian,
    Italian,
    Japanese,
    Kannada,
    Korean,
    Marathi,
    Norwegian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    [Display(Name = "Simplified Chinese")] SimplifiedChinese,
    [Display(Name = "Simplified Chinese (Cantonese)")] SimplifiedChineseCantonese,
    [Display(Name = "Simplified Chinese (Hokkien)")] SimplifiedChineseHokkien,
    [Display(Name = "Simplified Chinese (Mandarin)")] SimplifiedChineseMandarin,
    [Display(Name = "Simplified Chinese (Nanchang)")] SimplifiedChineseNanchang,
    [Display(Name = "Simplified Chinese (Shanghainese)")] SimplifiedChineseShanghainese,
    [Display(Name = "Simplified Chinese (Sichuan)")] SimplifiedChineseSichuan,
    Slovak,
    Spanish,
    Swedish,
    Tamil,
    Telugu,
    Thai,
    [Display(Name = "Traditional Chinese")] TraditionalChinese,
    [Display(Name = "Traditional Chinese (Cantonese)")] TraditionalChineseCantonese,
    [Display(Name = "Traditional Chinese (Mandarin)")] TraditionalChineseMandarin,
    [Display(Name = "Traditional Chinese (Taiwanese)")] TraditionalChineseTaiwanese,
    Turkish,
    Urdu
}